### ISSUE TITLE
Contents in tabs are not well fit to Xperia M4 screen

### ISSUE THREAD

**Issue by zputnyq** [lihenggui/blocker#62]
Hi @lihenggui 
Thanks for the update.
I get another issue regarding the appearance of contents inside tabs (service, activity, receiver & content provider), they don't fully shown. I use blocker 1.1.53. My device OS is stock 6.0.1

https://user-images.githubusercontent.com/31039796/160611361-716c7960-f925-448a-8f80-52e9f5994184.mp4

**Comment by lihenggui** [comment]
Checking

**Comment by lihenggui** [comment]
Fixed.  575af0598f9bd8381837f48f13ee044ae6c63135

**Comment by dhdkrystal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zputnyq** [comment]
@lihenggui it still happens till the latest version.

https://user-images.githubusercontent.com/31039796/179032438-2a569600-9896-45bd-a2fb-deaa1d7ac298.mp4

**Comment by lihenggui** [comment]
Let me check

**Comment by lihenggui** [comment]
It should be fixed with this PR : https://github.com/lihenggui/blocker/pull/119

I am currently rewriting the application, the new UI shouldn't have this issue.
